CREATE DATABASE IF NOT EXISTS `bootcamp`;

USE `bootcamp`;

DROP TABLE IF EXISTS `products`;

CREATE TABLE `products` (
	id		INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	name	VARCHAR(100) NOT NULL,
	type	VARCHAR(100) NOT NULL,
	count	INT NOT NULL,
	price	DECIMAL(16,2) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `products` WRITE;

UNLOCK TABLES;
